config/routes.rb
Rails.application.routes.draw do
  get 'weather/index'
  root 'weather#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def index
    # Initialize tracer
    tracer = OpenTelemetry.tracer_provider.tracer('weather_app', '0.1.0')

    tracer.in_span('weather_request') do |span|
      span.set_attribute('city', params[:city])

      record_metrics do
        fetch_weather_data
      end

      respond_to do |format|
        format.html
        format.json { render json: @weather }
      end
    end
  end

  private

  def record_metrics
    # calculate request response time
    start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    yield
    end_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    response_time = (end_time - start_time) * 1000
  
    # update tracer with new data
    span = OpenTelemetry::Trace.current_span
    span.set_attribute('response_time', response_time)
    span.set_attribute('requests_per_minute', calculate_requests_per_minute)
  end

  def fetch_weather_data
    # Add default value so we start page with something data
    @city = (params[:city] || 'Osaka').titleize
    service = WeatherService.new(ENV['OPENWEATHERMAP_API_KEY'])
    @weather = service.get_weather(@city)
  end

  def calculate_requests_per_minute
    current_time = Time.now
    recent_requests = request_timestamps.select { |timestamp| current_time - timestamp <= 60 }
    recent_requests.size
  end

  def request_timestamps
    timestamps = Rails.cache.fetch('request_timestamps') { [] }
    timestamps.reject! { |timestamp| Time.now - timestamp > 60 }
    timestamps
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather App</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/weather/index.html.erb
<%= form_tag(weather_index_path, method: :get) do %>
  <%= text_field_tag :city, @city, placeholder: 'Input City Name', class: 'input-field' %>
  <%= submit_tag 'Get Weather', class: 'submit-button' %>
<% end %>

<div class="weather-info">
  <% if @weather.present? && @weather['main'].present? %>
    <p>The current weather in <%= @city %> is:</p>
    <p>Temperature: <%= @weather['main']['temp'] %>°C</p>
    <p>Humidity: <%= @weather['main']['humidity'] %>%</p>
    <p>Wind Speed: <%= @weather['wind']['speed'] %>m/h</p>
  <% else %>
    <p>No weather forecast for <%= @city %>. Please check spelling and try again</p>
  <% end %>
</div>